### ISSUE TITLE
allow user-defined per-request log fields

### ISSUE THREAD

**Issue by ryepup** [ziflex/lecho#18]
I'm using [opentelemetry (otel)](https://opentelemetry.io/docs/instrumentation/go/) to trace my echo requests, and I would like the otel `traceID` to be a field in the logs made by `lecho`. Currently `lecho` has special handling for `X-Request-ID`, it would be great if that were extensible.

My current workaround is a partial fork of `lecho` using echo's [`middleware.RequestLoggerWithConfig`](https://pkg.go.dev/github.com/labstack/echo/v4/middleware#RequestLoggerWithConfig), and it'd be nice to drop that.

One possible API would look something like:

```go
e := echo.New()
logger := lecho.New(os.Stdout)
e.Logger = logger
e.Use(lecho.Middleware(
	lecho.Config{Logger: logger},
	lecho.WithPerRequestFields(func (c echo.Context, evt *zerolog.Event){
		// TODO: pull traceID off `c`, add to `evt`
	}),
))	
```

or maybe lump it into the `logger` itself:

```go
e := echo.New()
logger := lecho.New(os.Stdout, lecho.WithPerRequestFields(func (c echo.Context, evt *zerolog.Event){
	// TODO: pull traceID off `c`, add to `evt`
}))
e.Logger = logger
e.Use(lecho.Middleware(lecho.Config{Logger: logger}))	
```

Would you be open to this kind of addition?

**Comment by ziflex** [comment]
hey, I'm open to the feature itself, but not sure I'm sold on the implementation proposal.

I will think about how to implement it.

**Comment by ziflex** [comment]
Hey,
I added ``RequestIDHeader`` option to the Middleware configuration.

```go
e.Use(lecho.Middleware(lecho.Config{
    Logger:          logger,
    RequestIDHeader: "traceID",
}))
```
Will it be sufficient for you? Or you need both?

**Comment by ziflex** [comment]
Here is a way to enrich the logger with additional values:
https://github.com/ziflex/lecho/pull/19

Let me know if it works for you.

**Comment by ryepup** [comment]
That looks great, very extensible.
