### ISSUE TITLE
For an old version of Echo

### ISSUE THREAD

**Issue by ReplicAPI** [ziflex/lecho#2]
May I suggest you tweak this code to adapt it to Echo Framework v4? It's probably worth keeping lecho and forking it to lechov4.

**Comment by ziflex** [comment]
@ReplicAPI hey, thanks for the good idea!

**Comment by ziflex** [comment]
Migrated. 
Now you can pull down a new version of Lecho like this ``go get github.com/ziflex/lecho/v2``
